export const dashboardStyles = {
  dashboardContainerStyle: {
    pl: "32px",
    pt: "20px",
    pb: "20px",
  },
  lastExecutionDate: {
    fontFamily: "typography.fontFamily",
    fontSize: "14px",
    fontWeight: 400,
    color: "secondary.light",
  },
  costAndSummaryHeader: {
    fontFamily: "typography.fontFamily",
    fontSize: "20px",
    color: "secondary.main",
    fontWeight: 800,
  },
  dashboardTopBorderStyle: {
    borderTop: `1px solid `,
    borderTopColor: "secondary.contrastText",
    mt: "20px",
  },
  costContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    mb: "40px",
  },
  costSummaryAndForcastStyle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: "8px !important",
    minHeight: "96px !important",
    pl: "16px !important",
    minWidth: "32%",
    pr: "16px !important",
    backgroundColor: "success.light",
    boxSizing: "border-box",
  } as const,
  forecastedAmountRange: {
    fontFamily: "typography.fontFamily",
    fontSize: "12px",
    color: "secondary.light",
    fontWeight: 400,
    ml: "4px",
  },
  resourcesInfo: {
    display: "inline",
    fontFamily: "typography.fontFamily",
    fontSize: "21px",
    fontWeight: 800,
    color: "secondary.light",
  },
  resourcesInfoContainer: {
    width: "750px",
    height: "224px",
    backgroundColor: "success.light",
    borderRadius: "8px",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    pt: "32px",
    pb: "32px",
  } as const,
};
